// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa0z2Wmf66wS0D9YXjr3aW6dfRH1OkNM0',
    appId: '1:567755625765:web:f223f8037f2d533b8876cc',
    messagingSenderId: '567755625765',
    projectId: 'expense-tracker-71410',
    authDomain: 'expense-tracker-71410.firebaseapp.com',
    storageBucket: 'expense-tracker-71410.firebasestorage.app',
    measurementId: 'G-9SN73850H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi0W5GDQ3HB_grz8xiQuuNTeyQIi9cGAo',
    appId: '1:567755625765:android:6837798ab6a2d17b8876cc',
    messagingSenderId: '567755625765',
    projectId: 'expense-tracker-71410',
    storageBucket: 'expense-tracker-71410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZD1sCkA_-ft3KhL7IAMNTvkWGTq4mCL4',
    appId: '1:567755625765:ios:20e579a02b557a488876cc',
    messagingSenderId: '567755625765',
    projectId: 'expense-tracker-71410',
    storageBucket: 'expense-tracker-71410.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZD1sCkA_-ft3KhL7IAMNTvkWGTq4mCL4',
    appId: '1:567755625765:ios:20e579a02b557a488876cc',
    messagingSenderId: '567755625765',
    projectId: 'expense-tracker-71410',
    storageBucket: 'expense-tracker-71410.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa0z2Wmf66wS0D9YXjr3aW6dfRH1OkNM0',
    appId: '1:567755625765:web:a9c4918d4c8052038876cc',
    messagingSenderId: '567755625765',
    projectId: 'expense-tracker-71410',
    authDomain: 'expense-tracker-71410.firebaseapp.com',
    storageBucket: 'expense-tracker-71410.firebasestorage.app',
    measurementId: 'G-8Y4DW2RZWH',
  );
}
